"use client";

import type { ParentReportData } from "@/lib/insights/parent-report";
import { formatReportPeriod } from "@/lib/insights/parent-report";

export function ParentReportView({ report }: { report: ParentReportData }) {
  const mastery =
    report.masteryEnd !== null ? `${report.masteryEnd}%` : "—";

  return (
    <article className="parent-report mx-auto max-w-2xl space-y-6 rounded-xl border border-border bg-white p-8 text-stone-900 print:border-0 print:p-0">
      <header className="border-b border-stone-200 pb-4">
        <p className="text-xs uppercase tracking-wide text-stone-500">
          Progress Report
        </p>
        <h1 className="mt-1 text-2xl font-semibold">{report.studentName}</h1>
        <p className="text-sm text-stone-600">{report.circleName}</p>
        <p className="mt-2 text-sm font-medium">
          {formatReportPeriod(report.periodStart, report.periodEnd)}
        </p>
      </header>

      <section className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <Stat label="Memorized" value={String(report.memorizedVerses)} suffix="verses" />
        <Stat label="Reviewed" value={String(report.reviewedVerses)} suffix="verses" />
        <Stat label="Sessions" value={String(report.sessionCount)} />
        <Stat label="Mastery" value={mastery} />
      </section>

      {report.strengths.length > 0 && (
        <section>
          <h2 className="font-semibold text-emerald-800">Strengths</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
            {report.strengths.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ul>
        </section>
      )}

      {report.improvements.length > 0 && (
        <section>
          <h2 className="font-semibold text-amber-800">Areas for improvement</h2>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
            {report.improvements.map((s) => (
              <li key={s}>{s}</li>
            ))}
          </ul>
        </section>
      )}

      {report.topWeakAyat.length > 0 && (
        <section>
          <h2 className="font-semibold">Most problematic ayat</h2>
          <ul className="mt-2 space-y-1 text-sm">
            {report.topWeakAyat.map((w) => (
              <li key={`${w.surah}-${w.ayah}`}>
                {w.surahName} {w.ayah} ({w.mistakeCount} mistakes)
              </li>
            ))}
          </ul>
        </section>
      )}

      {report.teacherNotes.length > 0 && (
        <section>
          <h2 className="font-semibold">Teacher notes</h2>
          <ul className="mt-2 space-y-2 text-sm">
            {report.teacherNotes.map((n, i) => (
              <li key={i} className="rounded-lg bg-stone-50 px-3 py-2">
                {n.body}
              </li>
            ))}
          </ul>
        </section>
      )}

      <footer className="border-t border-stone-200 pt-4 text-xs text-stone-500">
        Generated by Itqan · {new Date().toLocaleDateString()}
      </footer>
    </article>
  );
}

function Stat({
  label,
  value,
  suffix,
}: {
  label: string;
  value: string;
  suffix?: string;
}) {
  return (
    <div className="rounded-lg bg-stone-50 p-3 text-center">
      <p className="text-xs text-stone-500">{label}</p>
      <p className="text-xl font-bold">{value}</p>
      {suffix && <p className="text-xs text-stone-500">{suffix}</p>}
    </div>
  );
}
